# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Estudent')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='estudent',
        ),
        migrations.AddField(
            model_name='enroll',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Subject'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Teacher'),
        ),
    ]
