# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20180525_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='final_note',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='enroll',
            name='first_note',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='enroll',
            name='second_note',
            field=models.FloatField(default=0),
        ),
    ]
