# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20180525_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudent',
            name='genre',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
