# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_teacher_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='academic.Subject'),
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together=set([('estudent', 'subject')]),
        ),
    ]
