# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20180526_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(to='academic.Teacher'),
        ),
    ]
