# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_auto_20180526_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='final_note',
            new_name='def_note',
        ),
    ]
