# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_auto_20180526_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, to='academic.Teacher'),
        ),
    ]
